dist: trusty
sudo: false
language: node_js
node_js:
  - 6
  - 8
before_install:
- npm install -g npm@latest
- npm install -g greenkeeper-lockfile@latest
before_script: greenkeeper-lockfile-update
script: npm run ci
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
after_failure: ls -al /home/travis/builds/holidayextras/jsonapi-server
notifications:
  email: false
